<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cellTable</name>
   <tag></tag>
   <elementGuidId>0c744012-76d6-49c1-9de5-4418d6e797ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[@id='${tableName}']/*/tr[${rowIndex}]/td[${columnIndex}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[@id='${tableName}']/*/tr[${rowIndex}]/td[${columnIndex}]</value>
   </webElementProperties>
</WebElementEntity>
